# TWBC Database Analysis

## 1. Show table Players

In [13]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('../data/processed/twbc.db')

# Query the players table
df_players = pd.read_sql("SELECT * FROM players", conn)

# Display the results
df_players

    player_id           nick             full_name  team_id
0           1        wbc1211           Wang Siyuan       18
1           2         wbc366           Wang Haoran        1
2           3     wbc3ifndef           Jakub Horák        3
3           4           wbca          Adam Horváth        2
4           5  wbcadelstepan         Libor Krejčíř        7
5           6       wbcalleb        Alexey Lebedev       13
6           7       wbcangst     Piotr Małowiejski       12
7           8       wbcashot       Ashot Avetisyan       15
8           9         wbcasz            Gábor Nagy        9
9          10          wbcbb     Bogdan Brachaczek       11
10         11      wbcbeetle       Michał Żukowski       11
11         12      wbcbogimp         Anton Efremov       16
12         13    wbcbromozel           Ilya Katsev       13
13         14           wbcc            Petr Žižka        2
14         15      wbcciaran          Ciarán Lucey        8
15         16    wbccoldmind   Stanislav Hyžík jr.       17
16         17    wbccrosslet    Karol Podwyszyński       12
17         18       wbccsaba         Csaba Kamarás       10
18         19           wbcd      František Fňukal        2
19         20     wbcdeafbat           Jan Kopecký        6
20         21  wbcdistilfire         Petr Podolský        4
21         22     wbcfojtman          Jakub Fojtík        5
22         23       wbcfurla          Ilya Muratov       13
23         24      wbcfuzaty          Michal Holec       17
24         25         wbcg3m             Igor Eged       14
25         26     wbcgenghis            Milán Nagy       14
26         27     wbcgeordie   Stanislav Hyžík sr.       17
27         28      wbchajnal       Hajnalka Kovács       16
28         29      wbcheater       Łukasz Majksner       15
29         30        wbciron        Zoltán Sonkoly        8
30         31       wbciwbtc          Lukáš Souček        3
31         32     wbckakosik            Eva Orlova       16
32         33   wbckaktuszka     Krisztina Kamarás       10
33         34    wbckremufka      Szczepan Łukasik       15
34         35       wbclasek       Zoltán Menyhárt        9
35         36   wbclojzeidon           Alois Mikeš        4
36         37        wbcmark          Márk Horváth        8
37         38      wbcmartez         Martin Muzika        3
38         39      wbcmatiss        Matīss Riherts       15
39         40       wbcmichi     Michal Ferdinandy       14
40         41       wbcmk108         Denis Kachaev       13
41         42       wbcmulan               Bai Liu       18
42         43  wbcnguyenminh      Nguyễn Công Minh       18
43         44     wbcnirvana         Róbert Pátkai        9
44         45     wbcpangbai        Zhang Haoxiang        1
45         46    wbcpeaceman           Paweł Nowak       12
46         47     wbcperoxid        Štěpán Tesařík        4
47         48       wbcpiggi           Matěj Holub        5
48         49      wbcplayer              Li Fuwen       18
49         50     wbcpuholek           Michał Zajk       11
50         51      wbcpurkys         Jan Purkrábek        6
51         52     wbcquantum     Adrian Fitzermann       11
52         53       wbcrichi      Richard Červenka       17
53         54      wbcrostas         Ferenc Rostás        9
54         55      wbcseabow         Jana Adámková       17
55         56         wbcset  Konstantin Solomatin       16
56         57       wbcshpek        Radim Kostlivý        6
57         58       wbcsiwer     Michał Pietrusiak       12
58         59      wbcskoupy             Vít Jiřík        7
59         60   wbctasemnice         Tomáš Palacký        5
60         61       wbctorpe      M. Nándor Halena       10
61         62        wbcuida           Liu Xiangbo        1
62         63     wbcvotocek         Jakub Šalajka        7
63         64  wbcwonderwall           Josef Holba        5
64         65        wbcyu20            Liu Wenhao        1
65         66        wbczoli         Zoltán László        8

## 2. Custom

In [14]:
df_tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'", conn)
df_tables

         name
0       teams
1     players
2     matches
3  sub_rounds
4    pairings

In [15]:
pd.set_option('display.max_rows', None)
pd.read_sql("""
    SELECT * FROM players
    LIMIT 20
    """, conn)

    player_id           nick            full_name  team_id
0           1        wbc1211          Wang Siyuan       18
1           2         wbc366          Wang Haoran        1
2           3     wbc3ifndef          Jakub Horák        3
3           4           wbca         Adam Horváth        2
4           5  wbcadelstepan        Libor Krejčíř        7
5           6       wbcalleb       Alexey Lebedev       13
6           7       wbcangst    Piotr Małowiejski       12
7           8       wbcashot      Ashot Avetisyan       15
8           9         wbcasz           Gábor Nagy        9
9          10          wbcbb    Bogdan Brachaczek       11
10         11      wbcbeetle      Michał Żukowski       11
11         12      wbcbogimp        Anton Efremov       16
12         13    wbcbromozel          Ilya Katsev       13
13         14           wbcc           Petr Žižka        2
14         15      wbcciaran         Ciarán Lucey        8
15         16    wbccoldmind  Stanislav Hyžík jr.       17
16         17    wbccrosslet   Karol Podwyszyński       12
17         18       wbccsaba        Csaba Kamarás       10
18         19           wbcd     František Fňukal        2
19         20     wbcdeafbat          Jan Kopecký        6

In [16]:
pd.read_sql("""
    select 
        full_name   "Full Name",
        t.name      "Team Name"
    from 
        players p
        left join teams t on p.team_id = t.team_id
    order by
        t.name
    """, conn)

               Full Name             Team Name
0            Wang Haoran                 China
1         Zhang Haoxiang                 China
2            Liu Xiangbo                 China
3             Liu Wenhao                 China
4           Adam Horváth             Czechia A
5             Petr Žižka             Czechia A
6       František Fňukal             Czechia A
7            Jakub Horák             Czechia B
8           Lukáš Souček             Czechia B
9          Martin Muzika             Czechia B
10         Petr Podolský             Czechia C
11           Alois Mikeš             Czechia C
12        Štěpán Tesařík             Czechia C
13          Jakub Fojtík             Czechia D
14           Matěj Holub             Czechia D
15         Tomáš Palacký             Czechia D
16           Josef Holba             Czechia D
17           Jan Kopecký             Czechia E
18         Jan Purkrábek             Czechia E
19        Radim Kostlivý             Czechia E
20         Libor Krejčíř             Czechia F
21             Vít Jiřík             Czechia F
22         Jakub Šalajka             Czechia F
23          Ciarán Lucey             Hungary A
24        Zoltán Sonkoly             Hungary A
25          Márk Horváth             Hungary A
26         Zoltán László             Hungary A
27            Gábor Nagy             Hungary B
28       Zoltán Menyhárt             Hungary B
29         Róbert Pátkai             Hungary B
30         Ferenc Rostás             Hungary B
31         Csaba Kamarás             Hungary C
32     Krisztina Kamarás             Hungary C
33      M. Nándor Halena             Hungary C
34     Bogdan Brachaczek              Poland A
35       Michał Żukowski              Poland A
36           Michał Zajk              Poland A
37     Adrian Fitzermann              Poland A
38     Piotr Małowiejski              Poland B
39    Karol Podwyszyński              Poland B
40           Paweł Nowak              Poland B
41     Michał Pietrusiak              Poland B
42        Alexey Lebedev                Russia
43           Ilya Katsev                Russia
44          Ilya Muratov                Russia
45         Denis Kachaev                Russia
46             Igor Eged              Slovakia
47            Milán Nagy              Slovakia
48     Michal Ferdinandy              Slovakia
49       Ashot Avetisyan  Team International A
50       Łukasz Majksner  Team International A
51      Szczepan Łukasik  Team International A
52        Matīss Riherts  Team International A
53         Anton Efremov  Team International B
54       Hajnalka Kovács  Team International B
55            Eva Orlova  Team International B
56  Konstantin Solomatin  Team International B
57   Stanislav Hyžík jr.  Team International C
58          Michal Holec  Team International C
59   Stanislav Hyžík sr.  Team International C
60      Richard Červenka  Team International C
61         Jana Adámková  Team International C
62           Wang Siyuan  Team International D
63               Bai Liu  Team International D
64      Nguyễn Công Minh  Team International D
65              Li Fuwen  Team International D

In [17]:
pd.read_sql("select * from matches", conn)

,match_id,tournament_round,team_a_id,team_b_id,match_result,source_url
0,1,1,2,1,1:0,https://sites.google.com/view/worldblitzcup/tw...
1,2,1,5,10,1:0,https://sites.google.com/view/worldblitzcup/tw...
2,3,1,9,8,0:1,https://sites.google.com/view/worldblitzcup/tw...
3,4,1,11,6,1:0,https://sites.google.com/view/worldblitzcup/tw...
4,5,1,12,7,1:0,https://sites.google.com/view/worldblitzcup/tw...
5,6,1,14,3,0:1,https://sites.google.com/view/worldblitzcup/tw...
6,7,1,15,16,1:0,https://sites.google.com/view/worldblitzcup/tw...
7,8,1,17,13,0:1,https://sites.google.com/view/worldblitzcup/tw...
8,9,1,18,4,0:1,https://sites.google.com/view/worldblitzcup/tw...
9,10,2,1,15,0:1,https://sites.google.com/view/worldblitzcup/tw...
10,11,2,3,5,1:0,https://sites.google.com/view/worldblitzcup/tw...
11,12,2,4,11,0:1,https://sites.google.com/view/worldblitzcup/tw...
12,13,2,6,14,0:1,https://sites.google.com/view/worldblitzcup/tw...
13,14,2,7,18,0:1,https://sites.google.com/view/worldblitzcup/tw...
14,15,2,8,2,1:0,https://sites.google.com/view/worldblitzcup/tw...
15,16,2,10,9,0:1,https://sites.google.com/view/worldblitzcup/tw...
16,17,2,13,12,1:0,https://sites.google.com/view/worldblitzcup/tw...
17,18,2,16,17,1:0,https://sites.google.com/view/worldblitzcup/tw...
18,19,3,2,16,1:0,https://sites.google.com/view/worldblitzcup/tw...
19,20,3,3,11,0:1,https://sites.google.com/view/worldblitzcup/tw...
20,21,3,4,12,0:1,https://sites.google.com/view/worldblitzcup/tw...
21,22,3,5,8,0:1,https://sites.google.com/view/worldblitzcup/tw...
22,23,3,7,14,0:1,https://sites.google.com/view/worldblitzcup/tw...
23,24,3,9,18,1:0,https://sites.google.com/view/worldblitzcup/tw...
24,25,3,10,1,0:1,https://sites.google.com/view/worldblitzcup/tw...
25,26,3,13,15,0:1,https://sites.google.com/view/worldblitzcup/tw...
26,27,3,17,6,0:1,https://sites.google.com/view/worldblitzcup/tw...